configfile: "../../snakemake-config.yaml"

import os
import json
import itertools
from icat.src import snakemake_utils as utils

# this is unecessary, but prevents flagged erros in editors
try:
    config
except NameError:
    config = {}

INPUT_JSON = os.path.join('../../', config['simulations']['json'])
FILES = ['X.csv', 'obs.csv', 'var.csv']
CONDITIONS = ['Controls', 'Treated']
EXPERIMENTS = utils.get_simulation_ids(INPUT_JSON,
                                       config['simulations']['sims'],
                                       config['simulations']['reps'])

expected_out = ["../../data/processed/simulated/{exp}/{treat}/{out}".\
                format(exp=exp, treat=treat, out=out)\
                for exp, treat, out in itertools.product(EXPERIMENTS,
                                                         CONDITIONS, FILES)]
rule all:
    input:
        expected_out

rule simulate_data:
    input:
        json=os.path.join('../../', config['simulations']['json']),
    params:
        sims=config['simulations']['sims'],
        reps=config['simulations']['reps'],
        outdir="../../data/processed/simulated/"
    output:
        data=expected_out,
        csv="../../data/processed/simulated/simulations.csv"
    script:
        "../../src/generate_simulated_datasets.py"